apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-stage
  labels:
    app: auth
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth
        tier: backend
        env: production
    spec:
      containers:
      - name: auth
        image: raphaelfp/auth
        imagePullPolicy: Always
        env:
        - name: JWT_SECRET
          value: <JWT_SECRET>
        - name: MONGO_URI
          value: mongodb://mongo:27017/auth
        - name: PORT
          value: 3000
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi