apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-stage
  labels:
    app: auth
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth
        tier: backend
        env: production
    spec:
      containers:
      - name: auth
        image: raphaelfp/auth
        imagePullPolicy: Always
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt
              key: secret
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo
              key: uri
        - name: PORT
          value: '3000'
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi