apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodetest-production
  labels:
    app: nodetest
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nodetest
        tier: backend
        env: production
    spec:
      containers:
      - name: nodetest
        image: raphaelfp/nodetest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi