apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pod-template
  labels:
    app: pod-template
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-template
        tier: backend
        env: production
    spec:
      containers:
      - name: pod-template
        image: raphaelfp/pod-template
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi