apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodetest
  name: nodetest
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: nodetest
    tier: backend
  sessionAffinity: None
  type: LoadBalancer