apiVersion: v1
kind: Service
metadata:
  labels:
    app: pod-template
  name: pod-template
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: pod-template
    tier: backend
  sessionAffinity: None
  type: LoadBalancer